[build]
  publish = "/"
  base = "."

# توجيهات CMS الأساسية (لحل مشكلة /admin/ 404)
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# توجيهات Netlify Identity (لحل مشكلة رابط الدعوة/إعادة التعيين)
[[redirects]]
  from = "/.netlify/identity"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/.netlify/identity/*"
  to = "/index.html"
  status = 200